import { Routes, Route, useLocation } from 'react-router-dom';
import Create from './components/Create'
import View from './components/View'
import {useState, useEffect} from 'react'

function App() {

  // newCardID state is generated by firebase and collected on form submission, it is used in the unique URL path and retrieving respective data from firebase
  const [newCardID, setNewCardID] = useState("")

  let location = useLocation();
  useEffect(() => {
    // takes the path from useLocation and splits it to provide the id part of a unique URL
    let currentPath = location.pathname.split("view/")
    // If url has been entered with an id in the path, the id is set to newCardID state to assist data retrieve from firebase
    if (currentPath.length > 1) {
      setNewCardID(currentPath[1])
    }
}, [])

// Two routes, one to the Create component which houses the form. The other is where a card will be viewed, dynamically taking newCardID as part of the path 
  return (
    <Routes>
      <Route path={"/"} element={<Create setNewCardID={setNewCardID} newCardID={newCardID} />} />
      <Route path={`/view/${newCardID}`} element={<View newCardID={newCardID} />} />
    </Routes>
  );
}

export default App;
